#!/bin/bash
set -euo pipefail

nbconfig="$HOME/.config/newsboat/urls"
# Параметры прокси
proxy_host="localhost"  # Замените на адрес вашего прокси
proxy_port="1080"       # Замените на порт вашего прокси

die() {
    echo -e >&2 "Ошибка: $1"
    exit 1
}

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

check_dependencies() {
    local dependencies=(
        "shup:https://github.com/pystardust/shup"
        "curl:https://curl.se/download.html"
    )
    local missing=()

    for dep in "${dependencies[@]}"; do
        local cmd=${dep%%:*}
        local url=${dep#*:}
        if ! command -v "$cmd" &> /dev/null; then
            missing+=("$cmd ($url)")
        fi
    done

    if [[ ${#missing[@]} -gt 0 ]]; then
        die "Отсутствуют зависимости:\n$(printf '%s\n' "${missing[@]}")"
    fi
}

extract_rss() {
    local link=$1
    curl -s --socks5 "$proxy_host:$proxy_port" "$link" | shup "link[RSS]" | grep -Po '(?<=href=").+?(?=")'
}

add_rss_to_config() {
    local rss=$1
    local name=$2
    if grep -Fq "$rss" "$nbconfig"; then
        log "$rss уже есть в $nbconfig"
    else
        if [[ -z "$name" ]]; then
            rssstring="$rss \"001: youtube\""
            rssname="RSS"
        else
            rssstring="$rss \"001: youtube\" \"~$name\""
            rssname="RSS \"$name\""
        fi
        echo "$rssstring" >> "$nbconfig"
        log "$rssname добавлен в $nbconfig"
    fi
}

main() {
    check_dependencies

    # Проверка наличия аргументов
    if [[ $# -eq 0 ]]; then
        die "Не указана ссылка\nИспользование: ytrss <ссылка> [имя]"
    fi

    local link=$1
    local name=${2:-}  # Если второй аргумент не передан, используем пустую строку

    local rss=$(extract_rss "$link")
    add_rss_to_config "$rss" "$name"
}

main "$@"
